-- V1__initial_schema.sql
-- Initial database schema for the e-shop application.
-- Column types match what Hibernate expects so ddl-auto=validate passes.

-- ----------------------------------------------------------
-- Users
-- ----------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    name          VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- ----------------------------------------------------------
-- Categories
-- ----------------------------------------------------------
CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT categories_name_unique UNIQUE (name)
);

-- ----------------------------------------------------------
-- Products
-- ----------------------------------------------------------
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    price       NUMERIC(10,2) NOT NULL,
    image       VARCHAR(255)  NOT NULL,
    category_id BIGINT        NOT NULL,
    CONSTRAINT products_category_fk FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- ----------------------------------------------------------
-- Orders
-- ----------------------------------------------------------
CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    created_at    TIMESTAMP(6) WITH TIME ZONE,
    customer_name VARCHAR(255)  NOT NULL,
    phone         VARCHAR(255)  NOT NULL,
    address_line  VARCHAR(255)  NOT NULL,
    city          VARCHAR(255)  NOT NULL,
    zip           VARCHAR(255)  NOT NULL,
    total         NUMERIC(38,2) NOT NULL,
    status        VARCHAR(255)  NOT NULL,
    CONSTRAINT orders_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT orders_status_check CHECK (
        status IN ('NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')
    )
);

-- ----------------------------------------------------------
-- Order items
-- ----------------------------------------------------------
CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL,
    product_id BIGINT,
    title      VARCHAR(255),
    price      NUMERIC(12,2) NOT NULL,
    image      VARCHAR(255),
    category   VARCHAR(255),
    qty        INTEGER,
    line_total NUMERIC(12,2) NOT NULL,
    CONSTRAINT order_items_order_fk FOREIGN KEY (order_id) REFERENCES orders(id)
);
