-- V3__product_variants_and_size_types.sql
-- Adds per-size stock tracking for clothing and shoes.
--
-- Why: The shop sells clothing and shoes, which come in sizes.
-- We need to know how many of each size are in stock so customers
-- can't buy a Medium hoodie when we only have Large in stock.

-- ----------------------------------------------------------
-- 1) Categories now declare what KIND of sizes their products use.
--
--    CLOTHING -> S, M, L, XL, XXL
--    SHOE     -> 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48
--
--    The actual list of size labels lives in the application
--    (it's static, doesn't belong in the DB). The DB only stores
--    which "bucket" a category belongs to.
-- ----------------------------------------------------------
ALTER TABLE categories
    ADD COLUMN size_type VARCHAR(20) NOT NULL DEFAULT 'CLOTHING';

ALTER TABLE categories
    ADD CONSTRAINT categories_size_type_check
    CHECK (size_type IN ('CLOTHING', 'SHOE'));

-- Classify the seed categories from V2.
-- (After this, new categories added via admin UI must specify a size_type.)
UPDATE categories SET size_type = 'SHOE'     WHERE name = 'Shoes';
UPDATE categories SET size_type = 'CLOTHING' WHERE name IN ('T-Shirts', 'Hoodies');

-- ----------------------------------------------------------
-- 2) product_variants — one row per (product, size) combo.
--
--    Example for a Red Hoodie (product 42):
--      id | product_id | size | stock
--       1 |     42     |  S   |  12
--       2 |     42     |  M   |  25
--       3 |     42     |  L   |   7
--       4 |     42     |  XL  |   0   <- out of stock, greyed out in UI
--       5 |     42     |  XXL |   3
--
--    Price stays on products — it's the same for every size.
-- ----------------------------------------------------------
CREATE TABLE product_variants (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT  NOT NULL,
    size       VARCHAR(10) NOT NULL,
    stock      INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT product_variants_product_fk
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT product_variants_unique_size
        UNIQUE (product_id, size),
    CONSTRAINT product_variants_stock_check
        CHECK (stock >= 0)
);

-- ----------------------------------------------------------
-- 3) order_items remembers which size was bought.
--
--    We store size as a snapshot (not a FK to product_variants)
--    so order history still reads correctly even if a variant
--    is later deleted or renamed.
--
--    Nullable: old orders (placed before this migration) have no size.
-- ----------------------------------------------------------
ALTER TABLE order_items
    ADD COLUMN size VARCHAR(10);
