-- V6__order_status_history.sql
-- Per-order audit log of status transitions. Lets the customer-facing order
-- page show *when* each step happened, not just which step is current.
--
-- One row is inserted on order creation (status = NEW, changed_at = created_at)
-- and one extra row every time the admin moves the order to a new status.

CREATE TABLE order_status_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT       NOT NULL,
    status     VARCHAR(255) NOT NULL,
    changed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT order_status_history_order_fk
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT order_status_history_status_check CHECK (
        status IN ('NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')
    )
);

-- Fast lookup of a single order's history, sorted newest-last.
CREATE INDEX order_status_history_order_idx
    ON order_status_history (order_id, changed_at);

-- Backfill: every existing order gets one history row representing its
-- current status, stamped with the order's creation time. Without this,
-- old orders would appear to have no history at all on the order page.
INSERT INTO order_status_history (order_id, status, changed_at)
SELECT id, status, created_at
FROM orders;
