-- V7__discount_codes.sql
-- Admin-managed promotional codes (e.g. SAVE10 -> 10% off total).
--
-- Design notes:
--  * `code` is unique and stored upper-cased. We match case-insensitively
--    at order time, but the canonical form lives in upper case so the
--    admin doesn't create both "save10" and "SAVE10".
--  * `percent_off` is 1..100. A value of 100 means "free order" — we
--    leave that policy to the admin.
--  * `active` lets the admin disable a code without deleting it, keeping
--    any orders that already used it linkable by code for reporting.
--  * Orders snapshot the applied code + percent so history stays correct
--    even if the discount row is later deleted.

CREATE TABLE discount_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    percent_off INTEGER      NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT discount_codes_code_unique UNIQUE (code),
    CONSTRAINT discount_codes_percent_check CHECK (percent_off BETWEEN 1 AND 100)
);

-- Per-order snapshot of the discount that was applied, if any. Nullable
-- on purpose — most orders won't use a code.
ALTER TABLE orders
    ADD COLUMN discount_code    VARCHAR(50),
    ADD COLUMN discount_percent INTEGER;
